---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external
  namespace: network
  annotations:
    # Assign the external VIP
    io.cilium/lb-ipam-ips: "192.168.10.241"
    # Tell external-dns to create CNAME records pointing to external-obs.kalde.in
    # instead of A records pointing to the Gateway IP
    external-dns.alpha.kubernetes.io/target: "external-obs.kalde.in"
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*-obs.kalde.in"
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*-obs.kalde.in"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: kalde-in-wildcard-tls
            namespace: network
