apiVersion: v1
kind: Secret
metadata:
  name: external-dns-pihole-secret
  namespace: network
type: Opaque
stringData:
  EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:USIHKwLsx3upNSQwAdfwfGJyt3g=,iv:OPVBW3ufiAresvRb49F5AY+EgMFOfdODhm5SDIiIRZU=,tag:egtrToSiS04fyRrhCvra6Q==,type:str]
sops:
  age:
    - recipient: age189gqacgyls7puscnagahv8m0synjs3v8hkn8ur8w4c56g9vpdccshj2400
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSUlVNy8vTlE5UkYwNHVa
        c0ZIbzRGNkkwcnA3UGdrQkpmaEd4aWppVVg4ClVkQ3VORHd2RFVaSU5HRW1keGJV
        cUdWVXV5c1IzdmhNenEwOTZSUXU2eUkKLS0tIFVGZzFMNnhMeURzVXZJZmdwbVZR
        b2dVZWZoT1RxbEluRG5TaWh1alFiZkkKEcOVd7r2KYI2xFCwzUyQB26/yhjoY32l
        Cpu3kABGkzGOhJmmxRVBzIA+m0zbe1ebxoY3LDxKAFEDq7KJff3BQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-21T08:08:45Z"
  mac: ENC[AES256_GCM,data:em9L0aC86uulCA8DU39+mAcE63TVeMDm/QdcNwYtL7G1UjIBvS82ETunc4uy86THdWPzpyC5qtIkbiUZ5pduaGMEduFHYF9xixx4Ej/FjlDJdz80xNy2Rn7BYDAc4vqk1ct/wOoRC6459/MwHOkPDvrRbLtM0hOuKtPqtVyGxGc=,iv:8NaIcFz3GGuV6gVzUOc9w8dD0nZf6MidC2owGuuN+0A=,tag:hsPGFJ8g5HgzHzMIBHf1sg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
