---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./grafana.yaml
  - ./datasource-prometheus.yaml
  - ./datasource-loki.yaml
  - ./httproute.yaml
  - ./dnsendpoint.yaml
  - ./dnsendpoint-pihole.yaml
