---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./grafana.yaml
  - ./datasource-prometheus.yaml
  - ./datasource-loki.yaml
  - ./datasource-alertmanager.yaml
  - ./httproute.yaml
  - ./dnsendpoint-pihole.yaml
  - ./dashboard-node-exporter.yaml
  - ./dashboard-kubernetes-cluster.yaml
  - ./dashboard-kubernetes-views-pods.yaml
