---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: external-obs
  namespace: network
spec:
  endpoints:
    - dnsName: external-obs.kalde.in
      recordTTL: 1
      recordType: CNAME
      targets:
        - fd68babb-9557-427e-a0cb-1a4084734d58.cfargotunnel.com
