---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: flux-webhook
  namespace: network
  labels:
    external-dns.io/provider: cloudflare
spec:
  endpoints:
    - dnsName: flux-webhook-obs.kalde.in
      recordTTL: 300
      recordType: CNAME
      targets:
        - external-obs.kalde.in
