---
# Internal DNS record for Pi-hole - points to internal gateway IP
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: external-obs-pihole
  namespace: network
  labels:
    external-dns.io/provider: pihole
  annotations:
    external-dns.alpha.kubernetes.io/target: "192.168.10.241"
spec:
  endpoints:
    - dnsName: external-obs.kalde.in
      recordTTL: 300
      recordType: A
      targets:
        - 192.168.10.241  # obs cluster external gateway
