---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/alert-notification-v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: github-alert
  namespace: flux-system
spec:
  providerRef:
    name: github-receiver
  eventSources:
    - kind: GitRepository
      name: flux-system
      namespace: flux-system
  eventSeverity: info
  exclusionList:
    - "^.*health check.*$"
