---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kalde-in-wildcard
  namespace: network
spec:
  secretName: kalde-in-wildcard-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.kalde.in"
  dnsNames:
    - "*.kalde.in"
    - "kalde.in"
