---
originRequest:
  originServerName: "external.obs.kalde.in"

ingress:
  - hostname: "obs.kalde.in"
    service: &svc https://cilium-gateway-external.network.svc.cluster.local
  - hostname: "*.obs.kalde.in"
    service: *svc
  - service: http_status:404
