---
originRequest:
  originServerName: "external-obs.kalde.in"

ingress:
  - hostname: "*-obs.kalde.in"
    service: https://cilium-gateway-external.network.svc.cluster.local
  - service: http_status:404
