---
originRequest:
  noTLSVerify: true

ingress:
  - hostname: "obs.kalde.in"
    service: &svc http://cilium-gateway-external.network.svc.cluster.local:80
  - hostname: "*.obs.kalde.in"
    service: *svc
  - service: http_status:404
