---
# IMPORTANT: Fill in your secrets below, then encrypt with: sops -e -i kubernetes/components/common/sops/cluster-secrets.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: obs.kalde.in
  SECRET_CLOUDFLARE_EMAIL: # TODO: Add your Cloudflare email
  SECRET_CLOUDFLARE_API_TOKEN: # TODO: Add your Cloudflare API token
