# IMPORTANT: Fill in your secrets below, then encrypt with: sops -e -i kubernetes/components/common/sops/cluster-secrets.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:111J38cvF9UhM9dh,iv:Nwv81U52PpJnKG81np/xYjQPyki/iTqsqBoVH7Hacgk=,tag:bSvILuMNpGYnC54cpI8ikQ==,type:str]
  SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:FPkYpheezx++JRMfM9nVRQ==,iv:2eHusEDVdAcVIUrzZjH7U8XAgTPhIvxLooKM//859S0=,tag:8ZYSCJXv9gC1OOJaakXZaw==,type:str]
  SECRET_CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:A/fAXTbArQ+SCkR65BmvdD6LKrrMBKV1KHyt4uWLX4/BQkGZicRrkQ==,iv:QyUDkqDWxQQSARxXHmFEOEAcDngkfU7LOv5bKHvbXcM=,tag:AcO0CL/qsFDfrep3vzCcyg==,type:str]
sops:
  age:
    - recipient: age189gqacgyls7puscnagahv8m0synjs3v8hkn8ur8w4c56g9vpdccshj2400
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4K2JGd21SRWttUStUcGF3
        dHBrRHFtZ3UrSkNHcHZNYUVwc2R0Q09HWHpZCmErMWJIaG1zZUJkcmY1WXZNUldY
        aVFjS0cxS1lpNTFUVTBYVkgrdHkySTAKLS0tIEFoalJBZWlDczVoL2JFdXVhVDJN
        NzZjelpzQUhxZ1FqSmlmYllyZzhTY2cKXWrOyvYj4sW3J88AkOF1ki6loY4dJlEu
        zAy2LmUQsGUq+E/c1ctFby6bbtu7yCTGsJ1l20dYFemeFHWU8E5o6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-19T18:53:19Z"
  mac: ENC[AES256_GCM,data:PW6xW0jWCHvqIkny4ubXTK7uo7eePTTZxOXjRpg28csNG9euRb5Qk8360qfcKZUQozSUjg+pUSl8czZmANOXVl01xRKgLQgqPHlLH3yVcD41sPpsWgLW16D9/b+hWITfXeq/chcUeA2ac8eQm1+2VafadU4oqHUYmgkGHQ6tR40=,iv:SLPjpietfTjMxXf2HIQQ+lRAO3H78ekRLlwe9LFpbuo=,tag:hhMs1kdWfC2EWo4VLGr2Rw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
