# IMPORTANT: This file contains the age secret key - encrypt with: sops -e -i kubernetes/components/common/sops/sops-age.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
stringData:
  age.agekey: ENC[AES256_GCM,data:laypo4bijiCoynZC7Z+3UMCbBAcVKAYpf8LW6RqgT95xxpKRL6HQwYrXUUM/dl3TE+07VxqCYeysFmGs5kg29mpmvVWj9v+0DfNR8NeaNRqMjpu5BdNLTt5dNs5zlnqmlr1EH0q4MslXQ3UfDFZxBAWOyYDUjixP5VRPiOQgeM2rhqkS35kq85ftGmGImFdRCdut/XC2k47bgnz26uwGTImgLeNxi4PX4ZkBjYrAl+TEJ94Q+YZ0jxzT7+l4,iv:93JEsUCWXjx5oviVaEi5AxsP0j17Lbt3KiWxhNvCeQI=,tag:wPhnDhHuYbdb0g8QcnE0Vg==,type:str]
sops:
  age:
    - recipient: age189gqacgyls7puscnagahv8m0synjs3v8hkn8ur8w4c56g9vpdccshj2400
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSWxLd01CNE9mSnNJZ1R4
        SmIwUzVlOG5EdXRqcGVXWjR6cVluWGd1TG1nCnYxcUE4VTkzUUp5YUQxUXVjTmVy
        UnNTaHFGbjJRbkdrZVpkdnBkaHJqemsKLS0tIFRIUXVDL2xzTW9SRlY2NlhxM1B3
        MFFWS3cxREZMVG1LSzliL21qV1I1SDgKB+DiQfgn/Mvm1HiSxRqXR6JegCvfn63L
        4SAsxPs6kJhQPXacNMMk4r0ITXmuyfzmCwg8+H/oxRrtANKvx/PdyQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-19T18:53:46Z"
  mac: ENC[AES256_GCM,data:dzvc9vA9CoOKMosnTx+Mzz0TwhtauNyArjvam6vEDvfSGmDXggQio0I6Cxf71A+gmmnFj5oGsXxcjwttJu3bPiK3mN8wWd1s8YjAAlZXVqqbw3vGiQK7fHf2rP54OzdBLYbG8UvburjueJQ+bHzMQyatOAuOvAkH3vr/E/NYduY=,iv:KE66MdKdfJPuY9XrYRJt3NCwt5ZHPiMxjWtQmqJMkrk=,tag:0sOQ7cnlsGGH8jSjicMJoA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
