---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cilium/ks.yaml
  - ./cert-manager/ks.yaml
  # cloudflare-dns removed - using internal-only DNS via Pi-hole
  - ./cloudflare-tunnel/ks.yaml
  - ./external-dns-pihole/ks.yaml
